### ISSUE TITLE
create "main" method for CLI, implement argument parsing

### ISSUE THREAD

**Issue by mathematicalmichael** [mindthegrow/cafelytics#10]
cafelytics/src/Worksheet.m is like a precursor to a notebook. 

I want the user to interact with this as follows:
```
python simulate_growth.py --farm ./data/farm.xlsx --growth ./data/growth.yml --strategy ./interventions/strategy1.yml --years 60
```

**Comment by mathematicalmichael** [comment]
what this does is
- load data from files specified
- passes them to growth simulation
- plots results (saves plots)

basically, I should have all I need to know after running that command.

**Comment by djdebonis** [comment]
What belongs in the "growth.yml" document? Everything else is clear, though!

**Comment by mathematicalmichael** [comment]
the assumptions for how different species grow I believe is the thought. It was previously in the same document as the farm info, but should be separated. give the option to override default assumptions. for now don't worry about it, we can add that 'load features from file' aspect later

**Comment by mathematicalmichael** [comment]
> What belongs in the "growth.yml" document? Everything else is clear, though!

Ah looks looks like you used `trees.yaml` for this in #15, same idea.
