### ISSUE TITLE
simulate cooperative

### ISSUE THREAD

**Issue by mathematicalmichael** [mindthegrow/cafelytics#11]
won't necessarily be named main, `simulate_cooperate(dataFrame, time, etc)`

It should not be doing data loading.

**Comment by mathematicalmichael** [comment]
In fact, this should be probably done with classes. "farm" class with attributes about the land itself. 
"cooperative" is comprised of a collection of farms.

Main method (`simualte_cooperative`) takes in a Farm class that has already been "built" .
Interventions are something passed to this function, not attributes that belong to the class.

**Comment by mathematicalmichael** [comment]
flow:

observe state
perform action
simulate year
repeat

**Comment by mathematicalmichael** [comment]
https://knightscholar.geneseo.edu/cgi/viewcontent.cgi?article=1083&context=proceedings-of-great-day @djdebonis

**Comment by djdebonis** [comment]
Interventions will  be called and assigned by main function, but the farm class will likely Have helper member functions that alter the attributes accordingly (e.g. farm.prune(year, proportion, etc).
