### ISSUE TITLE
variable naming/labeling

### ISSUE THREAD

**Issue by djdebonis** [mindthegrow/cafelytics#13]
for best practice: while translating, all significant numbers should be assigned to variables with descriptive names and/or the lines in which they are used should be commented. Many already have this, but, for example,

```octave
if n ==18:
    data(1,13)=20;
```

should be something like:

```python
pruneThreshold = 18 # description of what 'pruneThreshold' means (fake var name)
if n == pruneThreshold: # if the year is pruneThreshold, coffee plants explode
    data[1][13] =20;
```

**Comment by mathematicalmichael** [comment]
closeable?
