### ISSUE TITLE
understanding early pruning

### ISSUE THREAD

**Issue by djdebonis** [mindthegrow/cafelytics#16]
Trying to understand the [numbers being used](https://github.com/mathematicalmichael/cafelytics/blob/master/src/ProdSimulation.m#L30-L37) for  the early pruning simulation. Is  this implying that giving the trees early pruning gives them an  *extra* 20 years of life? I also don't see production being affected, only years of production. This very well could be my lack of exp with matlab.

If you had ten  minutes, something that would be extremely helpful is a brief summary of how production numbers (e.g. proportion of full harvest; years of production) change as a result of (1) pruning and (2)  intercropping.

**Comment by mathematicalmichael** [comment]
@djdebonis status? if done, leave some commentary and close it out

**Comment by mathematicalmichael** [comment]
I think you got the description. It initially lowers production but extends time. The details are long gone from memory but the write-up likely has an in-depth explanation.

**Comment by djdebonis** [comment]
numbers are adjustable through the strategy.yml files. right now it can impact both total production 'per tree' as well as the lifespan of the trees (according to input discretion).

**Comment by mathematicalmichael** [comment]
@djdebonis wanna give me a demo some time?
