### ISSUE TITLE
representative dataset

### ISSUE THREAD

**Issue by djdebonis** [mindthegrow/cafelytics#18]
now that the CLI is successfully returning plots (somewhat) resembling the original:
- [ ] tweak fakeData.py (probabilities, selections, etc.)
- [ ] run a script that lets you sift through data options

until

- [ ] we find a demo data set that somewhat resembles the data from the actual coop

**Comment by djdebonis** [comment]
not currently/ no longer in the scope of this project to mimic data

**Comment by mathematicalmichael** [comment]
> not currently/ no longer in the scope of this project to mimic data

okay fair, but you technically already did all that work. is it still committed? or at least on your laptop? 

my thinking is that it would be useful to generate some fake data as a case-study for reproducing the cooperative itself

**Comment by djdebonis** [comment]
Yes I still Have a copy of it somewhere and that copy also includes extra steps I took to make it even closer to resembling the coop by increasing the probability that ~30-50% of the trees would be planted within a 3-4 year range

**Comment by djdebonis** [comment]
I'll add it to my inDev branch later with a doc string that explains it
