### ISSUE TITLE
closing issues with keywords in commits

### ISSUE THREAD

**Issue by djdebonis** [mindthegrow/cafelytics#19]
Moving forward, I will be closing issues with keywords in commits when the commit solves the specific issue. I was not aware of this function until now.

https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by mathematicalmichael** [comment]
ohhhh this is amazing. I saw that if you comment on it in a PR it _sometimes_ closes the issue.

[EDIT] oh... wow. apparently "the default branch" is key there. when something merges into develop, it wont close the issue. when develop hits master, it probably will
