### ISSUE TITLE
use the `str` library or something similar to standardize stripping/formatting instead of trying to catch this

### ISSUE THREAD

**Issue by djdebonis** [mindthegrow/cafelytics#41]
use the `str` library or something similar to standardize stripping/formatting instead of trying to catch this

_Originally posted by @mathematicalmichael in https://github.com/mathematicalmichael/cafelytics/pull/39#discussion_r473558116_

**Comment by mathematicalmichael** [comment]
not handling user errors. if string representing a species is mis-typed (no direct match in existing config registry), then throw an error and make them fix it. front-end would handle creating species -> associated config + associated harvest event.
