### ISSUE TITLE
class object initialization strategy

### ISSUE THREAD

**Issue by djdebonis** [mindthegrow/cafelytics#43]
discover:

in python is it acceptable to call member functions in the initializer to help abstract the bulk of the code away from the __init__ function? In c++ this behavior is deprecated, however c++ is much different in regards to scope &  user accessability so it may not apply here. 

example:

with member function calls:

```python
class Farmarelli:
    def __init__(self, eventRows:pd.DataFrame, initialYear:int):
        self.assignParameters()
``` 

where `self.assignParameters()` assigns member variables?

or should these simply be assigned directly in the `__init__` function?

**Comment by djdebonis** [comment]
This question is still relevant, and it seems especially so when talking about inheritence (not sure if that will be applicable to the scope of *this* project, but surely in future work). 

I'm discovering that some variables ought to be initialized directly in the  `__init__` function because otherwise you end up passing parameters twice, which seems redundant. However, there is still a lot of abstraction that can be done if we choose the functional approach.

**Comment by mathematicalmichael** [comment]
generally these are handled by `__init__` method, and you think carefully about[ "separation of concerns" ](https://en.wikipedia.org/wiki/Separation_of_concerns) to avoid having too much bloat in there. Of course, not always possible... but... that's the idea. I think the idea is that `init` is already basically the equivalent of the function you're trying to define. If the problem you're trying to solve is that functions are getting lengthy... then think about "can this be done differently?" / "should this be a class?" 

I think functional is a good approach. Building software-as-a-service is an interesting approach. the idea is each function can in theory be deployed at an independent endpoint (server), taking inputs and returning some expected outputs. not saying everything should be done this way, just that it's an interesting approach that relies heavily on functional programming ideology.

**Comment by djdebonis** [comment]
thank you I will keep this in mind, most specifically:

>  then think about "can this be done differently?" / "should this be a class?"

as I'm moving forward.

**Comment by mathematicalmichael** [comment]
see new class structure. notice how minimal class initialization is. how there aren't any state changes within any of the classes over the course of the simulation (right now).
